name: CI

on:
  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [21, 22, 23]

    container: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Cache Dialyzer PLTs
        uses: actions/cache@v1
        with:
          path: ~.cache/rebar3/rebar3_*_plt
          key: ${{ runner.os }}-dialyzer-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.config')) }}
          restore-keys: |
            ${{ runner.os }}-dialyzer-
      - name: Compile
        run: rebar3 compile
      - name: EUnit
        run: rebar3 eunit
      - name: PropEr
        run: rebar3 proper
      - name: Run Checks
        run: rebar3 do dialyzer, xref
      - name: Create Cover Reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: rebar3 do cover, coveralls send
