name: CI

on:
  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [19, 20, 21, 22, 23]

    container: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: rebar3 compile
      - name: EUnit
        run: rebar3 eunit
      - name: PropEr
        run: rebar3 proper
